[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
itertools = "0.10.1"
serde_json = "1.0"
cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-compiler", branch = "main" }
cairo-lang-project = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-project", branch = "main" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-filesystem", branch = "main" }
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-sierra", branch = "main" }
cairo-lang-sierra-generator = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-sierra-generator", branch = "main" }
cairo-lang-diagnostics = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-diagnostics", branch = "main" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-syntax", branch = "main" }
cairo-lang-lowering = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-lowering", branch = "main" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-utils", branch = "main" }
cairo-lang-starknet-classes = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-starknet-classes", branch = "main" }
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-defs", branch = "main" }
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo/", package = "cairo-lang-starknet", branch = "main"}
